#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
if [[ $# -eq 1 ]]; then
    ping -c 5 "${1}"
else
    echo "Usage: 5-is_the_host_on_the_network ${0} {IP_ADDRESS}"
fi
