#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
minute=0
while [ $minute -le 60 ]
do
    if (( minute == 0)) ; then
        echo "Hour: 0"
    elif (( minute == 60 )) ; then
        echo "Hour: 1"
    else
        echo $minute
    fi
    (( minute++ ))
done

hour=1

while [ $hour -le 12 ]
do
    echo $hour
    (( hour++ ))
done
