#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo service nginx start
